repositories{
    maven {
        url "https://maven.saps.dev/minecraft"
        content {
            includeGroup "dev.ftb.mods"
        }
    }
    maven {
        url "https://maven.architectury.dev/"
    }
}

dependencies {
    implementation (group: 'org.mongodb', name: 'mongodb-driver-sync', version: '[5.3.0,)')
    implementation("dev.architectury:architectury-neoforge:${architectury_version}"){transitive = false}
    implementation("dev.ftb.mods:ftb-library-neoforge:${ftb_library_version}"){transitive = false}
    implementation("dev.ftb.mods:ftb-teams-neoforge:${ftb_teams_version}"){transitive = false}
    implementation("dev.ftb.mods:ftb-quests-neoforge:${ftb_quests_version}"){transitive = false}
}